config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  root 'static_pages#index'
  controller :bows do
    get :info
    get :contact
  end
  namespace :administrator do
    resources :bows do
      resources :photos
    end
  end
  resources :bows do
    resources :photos, only: [:show]
  end
  resources :charges

end

app/models/bow.rb
class Bow < ActiveRecord::Base
  has_many :photos
  belongs_to :user

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :bow
  belongs_to :user
  mount_uploader :picture, PictureUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bows
  has_many :photos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/administrator/bows_controller.rb
class Administrator::BowsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized

  def index
    @bows = Bow.all
  end

  def show
    @bow = Bow.find(params[:id])
    @photo = Photo.new
  end

  def new
    @bow = Bow.new
    @photo = Photo.new
  end

  def create
    Bow.create(bow_params)
    redirect_to administrator_bows_path
  end

  def edit
    @bow = Bow.find(params[:id])
  end

  def update
    @bow = Bow.find(params[:id])
    @bow.update_attributes(bow_params)
    redirect_to administrator_bows_path
  end


  def destroy
    @bow = Bow.find(params[:id])
    @bow.delete
    redirect_to administrator_bows_path
  end

  private

  def require_authorized
    if current_user.email != "administrator@admin.com"
      return render text: 'Unauthorized', status: :Unauthorized
    end
  end

  def bow_params
    params.require(:bow).permit(:name, :description)
  end

end

app/controllers/administrator/photos_controller.rb
class Administrator::PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized



  def create
    @bow = Bow.find(params[:bow_id])
    @bow.photos.create(photo_params)
    redirect_to administrator_bow_path(@bow)
  end

  private

  def require_authorized
    if current_user.email != "administrator@admin.com"
      return render text: 'Unauthorized', status: :Unauthorized
    end
  end

  def photo_params
    params.require(:photo).permit(:picture, :caption, :bow_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bows_controller.rb
class BowsController < ApplicationController

  def index
    @bows = Bow.all
  end

  def show
    @bow = Bow.find(params[:id])
    @photo = Photo.new
  end


  def info
  end

  def contact
  end

 
  private

  def bow_params
    params.require(:bow).permit(:name, :description)
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

def new
  redirect_to bows_path
end

def create
  # Amount in cents
  @amount = 10000

  customer = Stripe::Customer.create(
    :email => current_user.email,
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'KKA customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
     bows_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  protected

  def after_sign_in_path_for(resource)
    bows_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

end

app/helpers/administrator/bows_helper.rb
module Administrator::BowsHelper
end

app/helpers/administrator/photos_helper.rb
module Administrator::PhotosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bows_helper.rb
module BowsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/administrator/bows/edit.html.erb
<div class= "booyah-box-2 col-xs-10 col-xs-offset-1">
    <h1>Edit Bow Details</h1>
    <%= simple_form_for @bow, url: administrator_bow_path do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>      
          <br />
          <%= f.submit 'Update', class: 'btn btn-primary' %>
          <%= link_to 'Destroy', administrator_bow_path(@bow), method: :delete,  data: {confirm: 'Are you sure you want to delete this?'}, class: 'btn btn-danger' %>
    <% end %>
</div>

app/views/administrator/bows/index.html.erb
<html>
<style>
</style>
<body>
  <% @bows.each do |bow| %>
    <%= link_to bow_path(bow)  do %>
      <div class="booyah-box-1 col-xs-10 col-xs-offset-1" >
        <i><%= bow.name %></i>
        </br>
        <p><%= bow.description %></p>
        <% if bow.photos.present? %>
          <%= image_tag bow.photos.first.picture, class: "img-thumbnail" %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</body>
</html>

app/views/administrator/bows/new.html.erb
<div class= "booyah-box-2 col-xs-10 col-xs-offset-1">
    <h1>Enter Bow Details</h1>
    <%= simple_form_for @bow, url: administrator_bows_path do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :price %>
          <br />
          <%= f.submit 'Create', class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/administrator/bows/show.html.erb
<div class= "booyah-box-2 col-xs-12">
  <h1><%= @bow.name %></h1><br />
  <p><%= @bow.description %></p><br />

<% @bow.photos.each do |photo| %>
  <%= image_tag photo.picture, class: "img-responsive" %>
  <%= photo.caption %>
<% end %>
</div>


<div class="clear"></div>
<%= simple_form_for @photo, url: administrator_bow_photos_path(@bow) do |f| %>
  <%= f.input :picture %>
  <%= f.input :caption %>
  <%= f.submit "Add Photo", class: 'btn btn-primary' %>
<% end %>

app/views/bows/contact.html.erb
<!DOCTYPE html>
<html>
<style>
  body  { 
    background: url(../assets/bows_background2.jpg) no-repeat center center fixed; 
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
  }
</style>
<body>
  <div class="booyah-box-1 col-xs-10 col-xs-offset-1" >
      <h1>Contact Kevin's Kustom Archery</h1>
      <h2>This page is under construction</h2>
  </div>
</body>
</html>

app/views/bows/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bows | Kevins Kustom Archery</title>
<style>
</style>
</head>
<body>

<div class="container">
  <div class= "row">
  <br/>
<br/>
    <div class="frosty col-lg-8 col-lg-offset-2 text-center" style="position:relative;" >
      <br/>
      <h1>Featured Bows</h1>
      <br/>
    </div>
    <div>
      <% @bows.each do |bow| %>
        <%= link_to bow_path(bow)  do %>
          <div class="booyah-box-1 col-lg-3 col-sm-4 col-xs-10 col-xs-offset-1">
            <i><%= bow.name %></i>
            <% if bow.photos.present? %>
              <%= image_tag bow.photos.first.picture, class: "img-thumbnail" %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="frosty col-lg-8 col-lg-offset-2 text-center" style="position:relative;">
      <br/>
      <h1>Other Bow Shots</h1>
      <br/>
    </div>  
  </div>
</div>

</body>
</html>

app/views/bows/info.html.erb
<!DOCTYPE html>
<html>
<style>

</style>
<body>
<br/>
<br/>
  <div class="booyah-box-1 col-xs-10 col-xs-offset-1" >
      <h1>The Bowyer</h1>
      <h2>This page is under construction</h2>
  </div>
</body>
</html>

app/views/bows/show.html.erb
<!DOCTYPE html>
<html>
<style>

</style>
<body>
<br/>
<br/>
  <div class= "booyah-box-2  col-xs-12 col-md-10 col-md-offset-1">
    <h1><%= @bow.name %></h1><br />
    <p><%= @bow.description %></p><br />
    <p><strong>Love this bow? Want one like it? Press "Pay" to start your order! (Must be logged in)</strong></p>
    <p><strong>Got questions? Contact me <a href="/contact">here.</a></strong></p>
      <% if @bow.price? %>
        <%= form_tag charges_path do %>
          <article>
            <% if flash[:error].present? %>
              <div id="error_explanation">
                <p><%= flash[:error] %></p>
              </div>
            <% end %>
            <label class="amount">
              <span>Price: $<%= @bow.price %></span>
            </label>
          </article>
        <% if user_signed_in? %>
          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-description="<%= @bow.name %>"
                  data-amount="10000"
                  data-locale="auto"></script>
        <% end %>
        <% end %>
        <h6 style="font-style: italic"><strong>By pressing "Pay", you agree to pay a non-refundable deposit of $100 to complete your order.</strong></h6>
    <% end %>
  <br/>
  <% @bow.photos.each do |photo| %>
    <%= image_tag photo.picture, class: "img-responsive" %>
    <%= photo.caption %>
  <% end %>
  </div>
</body>
</html>

app/views/charges/create.html.erb
<%= render template: "layouts/application" %>
<br/>
<br/>
<div class="booyah-box-1 col-lg-4 col-lg-offset-4 col-xs-10 col-xs-offset-1 text-center" style="position: relative; margin-top: 100; margin-bottom: 0;">
	<h2>Thank you for your purchase!</h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Kevins Kustom Archery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

  <%= csrf_meta_tags %>
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
<% unless controller_name == "static_pages" %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href= "/" >Kevin's Kustom Archery</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=""><a href="/info">The Bowyer<span class="sr-only">(current)</span></a></li>
        <li><a href="/bows">The Bows</a></li>
      </ul>
 
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Log In', new_user_session_path %></li>
        <li><%= link_to 'Create an Account', new_user_registration_path %></li>
      <% end %>
        <li><a href="/contact">Contact</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<% end %>
<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-backstretch/2.0.4/jquery.backstretch.min.js"></script>
  <script>
    $.backstretch("../assets/bows_background2.jpg");
  </script>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<style>

</style>
  <body>
    <%= yield %>
  <script>
    $.backstretch("../assets/bows_background2.jpg");
  </script>
  </body>
</html>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Home | Kevins Kustom Archery</title>
</head>
<style>

.medium, .small { display:none }
@media screen and (max-width:760px) {
.desktop { display:none }
.medium { display:block }
}
@media screen and (max-width:320px) {
.medium { display:none }
.small { display:block }
}
</style>
</head>

<body>
  <div id="enter" class="frosty col-xs-10 col-xs-offset-1 text-center" style="position: absolute; margin-top: 0; margin-bottom: 0;">
      <br />
      <h1>Welcome</h1>
        <h2 class= changeFont><%= link_to "Come on in!", bows_path, class: 'myButton' %></h2>
      <h1>to my Workshop!</h1>
        <br />
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-backstretch/2.0.4/jquery.backstretch.min.js"></script>
  <script>
    $.backstretch("../assets/image_08.jpg");
  </script>
</body>
</html>
